### ISSUE TITLE
Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to expected argument type '[String : Any]?'

### ISSUE THREAD

**Issue by adiahuja07** [FabrizioBrancati/BFKit#36] opened 2018-07-17 13:41 UTC
I recently updates to Xcode 9.4 and I have got this error all over the NSAttributedString+Extentions.swift file.
I am on the 3.2.0 version of BFKIT.
What should I do to get over this?

Thanks in advance
![screen shot 2018-07-17 at 7 10 13 pm](https://user-images.githubusercontent.com/10696479/42820982-19242f0c-89f5-11e8-8e1e-96a7411d4004.png)

**Comment by FabrizioBrancati** [comment] 2018-07-17 22:00
This is the BFKit Objective-C project, but anyway, I have been able to integrate BFKit-Swift into a Swift project.
Can you post here your Podfile?
Are you integrating it into a Swift or an Objective-C project?

**Comment by adiahuja07** [comment] 2018-07-18 04:47
I am integrating it in Swift

Here is the podfile -
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Save Your Pocket' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Save Your Pocket
#pod 'APValidators'
#pod 'BWWalkthrough'
#pod 'Cartography'
#pod 'Colours/Swift'
#pod 'CoreStore'
#pod 'DynamicColor'
#pod 'EAIntroView'
#pod 'FacebookCore'
#pod 'FacebookLogin'
#pod 'FacebookShare'
#pod 'FlatUIKit'
#pod 'Instructions'
#pod 'Onboard'
#pod 'PureLayout'
#pod 'RZTransitions'
#pod 'RazzleDazzle'
#pod 'SVProgressHUD'
#pod 'Simplicity'
#pod 'Spring'
#pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
#pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'


pod 'Advance'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'AsyncSwift'
pod 'BFKit-Swift'
pod 'CZPicker'
pod 'DateToolsSwift'
pod 'Dollar'
pod 'EZSwiftExtensions'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Fluent'
pod 'FontAwesome.swift'
pod 'Format'
pod 'Google/SignIn'
#pod 'GoogleMaps'
#pod 'GooglePlacePicker'
#pod 'GooglePlaces'
pod 'IBAnimatable'
pod 'INTUAnimationEngine'
pod 'INTULocationManager'
pod 'JGProgressHUD'
pod 'Kingfisher'
pod 'SnapKit'
pod 'Sugar'
pod 'SwiftValidator'
pod 'SwiftyJSON'
pod 'Toast-Swift'
pod 'pop'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'TwitterKit'
pod 'MapboxNavigation'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

**Comment by adiahuja07** [comment] 2018-07-18 04:48
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Save Your Pocket' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Save Your Pocket
#pod 'APValidators'
#pod 'BWWalkthrough'
#pod 'Cartography'
#pod 'Colours/Swift'
#pod 'CoreStore'
#pod 'DynamicColor'
#pod 'EAIntroView'
#pod 'FacebookCore'
#pod 'FacebookLogin'
#pod 'FacebookShare'
#pod 'FlatUIKit'
#pod 'Instructions'
#pod 'Onboard'
#pod 'PureLayout'
#pod 'RZTransitions'
#pod 'RazzleDazzle'
#pod 'SVProgressHUD'
#pod 'Simplicity'
#pod 'Spring'
#pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
#pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'


pod 'Advance'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'AsyncSwift'
pod 'BFKit-Swift'
pod 'CZPicker'
pod 'DateToolsSwift'
pod 'Dollar'
pod 'EZSwiftExtensions'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Fluent'
pod 'FontAwesome.swift'
pod 'Format'
pod 'Google/SignIn'
#pod 'GoogleMaps'
#pod 'GooglePlacePicker'
#pod 'GooglePlaces'
pod 'IBAnimatable'
pod 'INTUAnimationEngine'
pod 'INTULocationManager'
pod 'JGProgressHUD'
pod 'Kingfisher'
pod 'SnapKit'
pod 'Sugar'
pod 'SwiftValidator'
pod 'SwiftyJSON'
pod 'Toast-Swift'
pod 'pop'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'TwitterKit'
pod 'MapboxNavigation'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

**Comment by FabrizioBrancati** [comment] 2018-07-18 06:53
The problem is that you are forcing the use of Swift 3.0, so you can use at most the version 2.6.0 as wrote in the [requirements section in the readme](https://github.com/FabrizioBrancati/BFKit-Swift#requirements)

**Comment by adiahuja07** [comment] 2018-07-18 06:56
Thanks alot man for the quick response, your right this should work.

**Comment by FabrizioBrancati** [comment] 2018-07-18 06:59
You are welcome 😉

**Comment by adiahuja07** [comment] 2018-07-18 07:54
After the last update most of the issues have gone away but 6 new issues have come up -
Argument labels '(rawValue:)' do not match any available overloads
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'
Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to expected argument type '[String : Any]?'


![screen shot 2018-07-18 at 1 22 07 pm](https://user-images.githubusercontent.com/10696479/42867653-db5401f4-8a8d-11e8-96c9-7f9f8bfb2084.png)

**Comment by FabrizioBrancati** [comment] 2018-07-18 08:10
That error is inside FontAwesome framework, not in BFKit-Swift, check the right version of FontAwesome that supports Swift 3

**Comment by adiahuja07** [comment] 2018-07-18 09:53
I have migrated from xcode 8 to xcode 9 and am having alot of problems in the pods installed. I know this isn't the right place to ask this but any help would be much appreciated.
![screen shot 2018-07-18 at 3 19 58 pm](https://user-images.githubusercontent.com/10696479/42874329-759ba748-8a9e-11e8-95bf-89c2a1deaed9.png)

**Comment by FabrizioBrancati** [comment] 2018-07-18 10:52
Maybe is better to remove this
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
``` 
from your Podfile, and migrate to the Swift 4 version of all your dependencies

**Comment by adiahuja07** [comment] 2018-07-19 05:55
If I make the swift_version to 3.2 will that be useful?

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

**Comment by FabrizioBrancati** [comment] 2018-07-19 06:54
Not so much, not currently, if you are planning to upgrade to Xcode 10 you should migrate to Swift 4.
Anyway, I think that you have to check if all your current version dependencies supports Swift 3.2

**Comment by adiahuja07** [comment] 2018-07-19 07:03
Alright I'll try something. This is the third day I'm spending on this problem.

**Comment by FabrizioBrancati** [comment] 2018-07-19 08:58
Since this is not releated to BFKit-Swift, can we close this?
If you will need more help, I will respond to you anyway 😄

**Comment by adiahuja07** [comment] 2018-07-19 10:04
Sure man, Thanks alot ;-D

**Closed** 2018-07-19 10:38 UTC
Labels: Question
